# Sample workflow for building and deploying a Hugo site to GitHub Pages
name: Call-HTTP-API

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

# Default to bash
defaults:
  run:
    shell: bash

jobs:
  call-api:
    runs-on: ubuntu-latest
    steps:
      - name: Call HTTP API
        run: curl -L -X POST -H 'Accept: application/vnd.github+json' -H 'Authorization: Bearer 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' -H 'X-GitHub-Api-Version: 2022-11-28' https://api.github.com/repos/foixes/gitbook/dispatches -d '{"event_type":"doc_deploy"}'
