name: Call HTTP API
on:
  push:
    branches: [ main ]

jobs:
  call-api:
    runs-on: ubuntu-latest
    steps:
      - name: Call HTTP API
        run: curl -L -X POST -H "Accept: application/vnd.github+json" -H "Authorization: Bearer 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" -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/repos/foixes/gitbook/dispatches -d '{"event_type":"doc_deploy"}'
